# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32c26c8989f6f566eda2ac39e9c7cffc53d4c61a6a45b9fcf5aab29e8719e8899c7596de16eaf83411b6200c73e144c0b5b91fcaedc70ebf32036620796ff140

test:
  secret_key_base: 8af1c191d66e16acf098b4518fd72d7bfa649a348da64cea7309aff4b5efb73c2a45f5c768565da8cf8f1dad661af5bcae251c080fda1de9c4ae0b458b281765

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
